autoDetectedPackages:
- com.fangyang.demo.utils
- com.hashmap
- com.java8.default_and_static_method
- com.java8.entity
- com.java8.lambda.beginning
- com.java8.lambda.practice
- com.java8.method_and_constructor_reference
- com.java8.new_time_api
- com.java8.optional
- com.java8.repeat_type_annotation
- com.java8.stream
enableAutoDetect: true
funcDisplayConfig:
  skipConstructors: false
  skipFieldAccess: true
  skipFieldChange: true
  skipGetters: true
  skipNonProjectPackages: true
  skipPrivateMethods: false
  skipSetters: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: smart
sourceDisplayConfig:
  color: blue
startOnDebug: false
